import { StyleSheet } from 'react-native'

const createStyles = (scale, palette, windowHeight = 800, windowWidth = 420) => {
  const isCompactMobile = windowWidth < 360
  const isUltraCompactMobile = windowWidth < 330

  return (
  StyleSheet.create({
    topBarActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isCompactMobile ? 6 : 8,
      marginRight: isCompactMobile ? 0 : 6,
    },
    topBarIconButton: {
      width: isCompactMobile ? 30 : 34,
      height: isCompactMobile ? 30 : 34,
      borderRadius: isCompactMobile ? 9 : 10,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    topBarIconButtonDisabled: {
      opacity: 0.5,
    },
    topBarTitleWrap: {
      flex: 1,
      justifyContent: 'center',
      minWidth: 0,
      paddingRight: 8,
      marginTop: 1,
    },
    topBarTitleWrapStacked: {
      flex: 1,
      width: '100%',
      paddingRight: 0,
      marginTop: 2,
      paddingLeft: 0,
      marginLeft: 0,
    },
    topBarInlineWrap: {
      width: '100%',
      backgroundColor: palette.cardBg,
      borderBottomWidth: 1,
      borderBottomColor: palette.borderSoft,
      paddingHorizontal: isCompactMobile ? 12 : 14,
      paddingTop: isCompactMobile ? 8 : 10,
      paddingBottom: isCompactMobile ? 10 : 12,
    },
    topBarHeaderRowStacked: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: isCompactMobile ? 8 : 10,
    },
    topBarBackButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBg,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    topBarHeaderContentStacked: {
      flex: 1,
      minWidth: 0,
    },
    topBarHeaderSectionStacked: {
      width: '100%',
      justifyContent: 'center',
      paddingBottom: 0,
    },
    topBarActionSectionStacked: {
      width: '100%',
      marginTop: isCompactMobile ? 4 : 5,
      paddingTop: isCompactMobile ? 10 : 12,
      minHeight: isCompactMobile ? 56 : 62,
      justifyContent: 'center',
      borderTopWidth: 1,
      borderTopColor: palette.borderSoft,
    },
    topBarTitleContent: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: isCompactMobile ? 8 : 12,
    },
    topBarTitleMain: {
      flex: 1,
      minWidth: 0,
      alignItems: 'flex-start',
    },
    topBarTitleMetaWrap: {
      minWidth: isUltraCompactMobile ? 58 : isCompactMobile ? 72 : 88,
      alignItems: 'flex-end',
      justifyContent: 'flex-start',
      paddingTop: isCompactMobile ? 0 : 2,
    },
    topBarChannelLogo: {
      width: isCompactMobile ? 22 : 26,
      height: isCompactMobile ? 22 : 26,
    },
    topBarTitleText: {
      color: palette.textPrimary,
      fontSize: (isCompactMobile ? 20 : 23) * scale,
      fontWeight: '900',
      lineHeight: (isCompactMobile ? 21 : 24) * scale,
    },
    topBarTitleIdentitySecondary: {
      marginTop: 2,
      color: palette.textSecondary,
      fontSize: isCompactMobile ? 10 : 11,
      fontWeight: '800',
      lineHeight: isCompactMobile ? 13 : 14,
    },
    topBarAppBadge: {
      marginTop: 2,
      alignSelf: 'flex-end',
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: isCompactMobile ? 7 : 9,
      paddingVertical: isCompactMobile ? 2 : 3,
    },
    topBarAppText: {
      fontSize: isCompactMobile ? 10 : 11,
      fontWeight: '900',
      letterSpacing: 0.25,
      textTransform: 'uppercase',
    },
    topBarStatusBadge: {
      marginTop: 4,
      alignSelf: 'flex-end',
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: isCompactMobile ? 7 : 9,
      paddingVertical: isCompactMobile ? 2 : 3,
    },
    topBarStatusText: {
      fontSize: isCompactMobile ? 10 : 11,
      fontWeight: '800',
      letterSpacing: 0.2,
      textTransform: 'uppercase',
    },
    topBarActionsStacked: {
      width: '100%',
      minHeight: isCompactMobile ? 46 : 50,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: isCompactMobile ? 6 : 8,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      borderRadius: isCompactMobile ? 12 : 13,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: isCompactMobile ? 9 : 10,
      paddingVertical: isCompactMobile ? 8 : 9,
    },
    mobileOrderScrollContent: {
      paddingBottom: isCompactMobile ? 138 : 126,
    },
    mobileOrderLayout: {
      gap: isCompactMobile ? 8 : 10,
    },
    mobileCompactSummaryCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBg,
      paddingHorizontal: isCompactMobile ? 10 : 12,
      paddingVertical: isCompactMobile ? 9 : 10,
    },
    mobileCompactSummaryGrid: {
      width: '100%',
    },
    mobileCompactSummaryItem: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: isCompactMobile ? 9 : 10,
      paddingVertical: isCompactMobile ? 7 : 8,
      gap: 6,
    },
    mobileCompactSummaryTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    mobileCompactSummaryMetric: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      minWidth: 0,
    },
    mobileCompactSummaryMetricFlexible: {
      flex: 1,
    },
    mobileCompactSummaryValue: {
      color: palette.textPrimary,
      fontSize: isCompactMobile ? 12 : 13,
      fontWeight: '800',
      lineHeight: isCompactMobile ? 14 : 15,
      flexShrink: 1,
    },
    mobileCompactSummaryValueStrong: {
      fontSize: isCompactMobile ? 13 : 14,
      lineHeight: isCompactMobile ? 15 : 16,
    },
    mobileCompactSummaryDateValue: {
      color: palette.textSecondary,
      fontSize: isCompactMobile ? 11 : 12,
      lineHeight: isCompactMobile ? 13 : 14,
    },
    mobileSummaryCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBg,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 2,
    },
    mobileSummaryHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
      gap: 10,
    },
    mobileSummaryOriginWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      gap: 8,
    },
    mobileSummaryOriginIcon: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBgSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mobileSummaryLabel: {
      color: palette.textSecondary,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    mobileSummaryValue: {
      color: palette.textPrimary,
      fontSize: 16,
      fontWeight: '900',
    },
    mobileSummaryIdentityWrap: {
      marginTop: 2,
      minWidth: 0,
    },
    mobileSummaryIdentityPrimary: {
      color: palette.textPrimary,
      fontSize: 24 * scale,
      fontWeight: '900',
      lineHeight: 28 * scale,
    },
    mobileSummaryIdentitySecondary: {
      marginTop: 2,
      color: palette.textSecondary,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 16,
    },
    mobileSummaryDateText: {
      marginTop: 4,
      color: palette.textSecondary,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 18,
    },
    mobileStatusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 4,
      backgroundColor: palette.cardBgSoft,
    },
    mobileStatusDot: {
      width: 8,
      height: 8,
      borderRadius: 999,
      marginRight: 6,
    },
    mobileStatusText: {
      color: palette.textPrimary,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    mobileSummaryMetricsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 10,
    },
    mobileDiscountPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    mobileDiscountText: {
      color: palette.accent,
      fontSize: 12,
      fontWeight: '800',
    },
    mobileWaitingPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.danger,
      backgroundColor: palette.dangerBg,
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    mobileWaitingText: {
      color: palette.dangerText,
      fontSize: 12,
      fontWeight: '800',
    },
    mobileSummaryFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderTopWidth: 1,
      borderTopColor: palette.border,
      paddingTop: 8,
      marginTop: 2,
      marginBottom: 6,
    },
    mobileTotalLabel: {
      color: palette.textSecondary,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.7,
    },
    mobileTotalValue: {
      color: palette.accentInfo,
      fontSize: 34 * scale,
      fontWeight: '900',
      lineHeight: 36 * scale,
    },
    mobileSummaryMetaList: {
      marginTop: 2,
      gap: 3,
    },
    mobileSummaryMetaText: {
      color: palette.textSecondary,
      fontSize: 12,
      fontWeight: '700',
    },
    mobileSummaryInfoBlock: {
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.border,
      paddingTop: 10,
      gap: 3,
    },
    mobileSummaryInfoTitle: {
      color: palette.accentInfo,
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 3,
    },
    mobileSummaryInfoText: {
      color: palette.textSecondary,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    mobileScheduledDeliveryCard: {
      marginTop: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#FCD34D',
      backgroundColor: '#FFFBEB',
      paddingHorizontal: 10,
      paddingVertical: 9,
      gap: 3,
    },
    mobileScheduledDeliveryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 1,
    },
    mobileScheduledDeliveryLabel: {
      color: '#92400E',
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    mobileScheduledDeliveryText: {
      color: '#78350F',
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    mobileFulfillmentCard: {
      marginTop: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#A7F3D0',
      backgroundColor: '#ECFDF5',
      paddingHorizontal: 10,
      paddingVertical: 9,
      gap: 3,
    },
    mobileFulfillmentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 1,
    },
    mobileFulfillmentLabel: {
      color: '#065F46',
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    mobileFulfillmentText: {
      color: '#065F46',
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    remoteStateBadge: {
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 3,
    },
    remoteStateBadgeText: {
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    mobileInfoCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBg,
      paddingHorizontal: isCompactMobile ? 10 : 12,
      paddingVertical: isCompactMobile ? 10 : 12,
      gap: isCompactMobile ? 8 : 10,
    },
    mobileInfoHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    mobileInfoIconWrap: {
      width: isCompactMobile ? 28 : 30,
      height: isCompactMobile ? 28 : 30,
      borderRadius: isCompactMobile ? 14 : 15,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBgSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mobileInfoTextWrap: {
      flex: 1,
    },
    mobileInfoLabel: {
      color: palette.textSecondary,
      fontSize: isCompactMobile ? 9 : 10,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.7,
      marginBottom: 1,
    },
    mobileInfoTitle: {
      color: palette.textPrimary,
      fontSize: (isCompactMobile ? 18 : 21) * scale,
      fontWeight: '900',
    },
    mobileInfoSubtitle: {
      color: palette.textSecondary,
      fontSize: isCompactMobile ? 11 : 12,
      fontWeight: '700',
      lineHeight: isCompactMobile ? 16 : 18,
      marginTop: 2,
    },
    inlineActionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    inlineActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isCompactMobile ? 5 : 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: isCompactMobile ? 9 : 11,
      paddingVertical: isCompactMobile ? 6 : 8,
    },
    inlineActionButtonPrimary: {
      borderColor: palette.accentInfo,
      backgroundColor: palette.cardBg,
    },
    inlineActionButtonDisabled: {
      opacity: 0.55,
    },
    inlineActionButtonText: {
      color: palette.accentInfo,
      fontSize: isCompactMobile ? 11 : 12,
      fontWeight: '800',
    },
    orderInvoiceBlockHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    orderInvoiceCounter: {
      color: palette.textSecondary,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    orderInvoiceList: {
      gap: 8,
    },
    orderInvoiceCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: isCompactMobile ? 10 : 11,
      paddingVertical: isCompactMobile ? 8 : 10,
      gap: isCompactMobile ? 5 : 6,
    },
    orderInvoiceCardInteractive: {
      backgroundColor: palette.cardBg,
    },
    orderInvoiceCardDetails: {
      backgroundColor: palette.cardBg,
    },
    orderInvoiceCardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
    },
    orderInvoiceCardHeaderActions: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 4,
    },
    orderInvoiceTitleWrap: {
      flex: 1,
      gap: 2,
    },
    orderInvoiceTitle: {
      color: palette.textPrimary,
      fontSize: 14 * scale,
      fontWeight: '800',
      lineHeight: 18 * scale,
    },
    orderInvoiceSubtitle: {
      color: palette.textSecondary,
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 16,
    },
    orderInvoiceStatusBadge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 4,
      alignSelf: 'flex-start',
    },
    orderInvoiceStatusText: {
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    orderInvoiceAmount: {
      color: palette.textPrimary,
      fontSize: 24 * scale,
      fontWeight: '900',
      lineHeight: 26 * scale,
    },
    orderInvoiceInfoGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    orderInvoiceInfoCard: {
      flexGrow: 1,
      minWidth: 132,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBg,
      paddingHorizontal: 10,
      paddingVertical: 8,
      gap: 3,
    },
    orderInvoiceInfoCardWide: {
      width: '100%',
    },
    orderInvoiceInfoLabel: {
      color: palette.textSecondary,
      fontSize: 10,
      fontWeight: '800',
      lineHeight: 12,
      textTransform: 'uppercase',
      letterSpacing: 0.35,
    },
    orderInvoiceInfoValue: {
      color: palette.textPrimary,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    orderInvoiceKind: {
      color: palette.textPrimary,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 17,
    },
    orderInvoiceMeta: {
      color: palette.textSecondary,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    marketplaceDeliveryPaymentCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 10,
      paddingVertical: 9,
      gap: 4,
    },
    marketplaceDeliveryPaymentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginBottom: 2,
    },
    marketplaceDeliveryPaymentTitle: {
      color: palette.accentInfo,
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    marketplaceDeliveryPaymentLine: {
      color: palette.textPrimary,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    marketplaceDeliveryPaymentLineStrong: {
      color: palette.textPrimary,
      fontSize: 12,
      fontWeight: '900',
      lineHeight: 17,
    },
    mobileAddressCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 10,
      paddingVertical: 9,
      flexDirection: 'row',
      gap: 8,
    },
    mobileAddressTextWrap: {
      flex: 1,
    },
    mobileAddressPrimary: {
      color: palette.textPrimary,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 19,
    },
    mobileAddressSecondary: {
      color: palette.textSecondary,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 18,
      marginTop: 2,
    },
    mobileTaxDocumentCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.accentInfo,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 10,
      paddingVertical: 9,
      flexDirection: 'row',
      gap: 8,
    },
    mobileTaxDocumentPrimary: {
      color: palette.accentInfo,
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 2,
    },
    mobileTaxDocumentSecondary: {
      color: palette.textPrimary,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    mobileNoteCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.accent,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    mobileNoteHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 4,
    },
    mobileNoteLabel: {
      color: palette.accent,
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    mobileNoteText: {
      color: palette.textPrimary,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    mobilePaymentGrid: {
      flexDirection: 'row',
      gap: 8,
    },
    mobilePaymentMetricCard: {
      flex: 1,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBg,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    mobilePaymentMetricLabel: {
      color: palette.textSecondary,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      marginBottom: 4,
      letterSpacing: 0.6,
    },
    mobilePaymentMetricValue: {
      color: palette.textPrimary,
      fontSize: 30 * scale,
      fontWeight: '900',
      lineHeight: 32 * scale,
    },
    mobilePaymentPendingValue: {
      color: '#D97706',
    },
    mobilePaymentMetricHint: {
      color: palette.textSecondary,
      fontSize: 11,
      fontWeight: '700',
      marginTop: 4,
    },
    mobileWarningCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.danger,
      backgroundColor: palette.dangerBg,
      paddingHorizontal: 11,
      paddingVertical: 9,
      gap: 4,
    },
    mobileWarningText: {
      color: palette.dangerText,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    mobileProductsCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBg,
      paddingHorizontal: isCompactMobile ? 8 : 10,
      paddingVertical: isCompactMobile ? 8 : 10,
      marginTop: 4,
      marginBottom: 6,
    },
    mobileProductsTitle: {
      color: palette.textSecondary,
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    purchaseItemRow: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: palette.cardBgSoft,
      marginBottom: 6,
      borderLeftWidth: 3,
      borderLeftColor: '#D97706',
    },
    purchaseItemTop: {
      flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8,
    },
    purchaseItemName: {
      flex: 1, fontSize: 14 * scale, fontWeight: '700', color: palette.textPrimary,
    },
    purchaseItemQty: {
      fontSize: 14 * scale, fontWeight: '800', color: '#D97706',
    },
    purchaseItemDesc: {
      fontSize: 12 * scale, color: palette.textSecondary, marginTop: 2,
    },
    purchaseItemComment: {
      fontSize: 12 * scale, color: palette.textSecondary, fontStyle: 'italic', marginTop: 4,
    },
    purchaseItemPriceRow: {
      flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6,
    },
    purchaseItemUnit: {
      fontSize: 12 * scale, color: palette.textSecondary,
    },
    purchaseItemTotal: {
      fontSize: 14 * scale, fontWeight: '800', color: '#D97706',
    },

    /* edição inline de itens */
    editItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      borderBottomColor: palette.borderSoft,
      gap: 8,
    },
    editItemName: {
      fontSize: 14 * scale,
      fontWeight: '700',
      color: palette.textPrimary,
    },
    editItemPrice: {
      fontSize: 12 * scale,
      color: palette.textSecondary,
      marginTop: 2,
    },
    editQtyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isCompactMobile ? 3 : 4,
    },
    editQtyBtn: {
      width: isCompactMobile ? 30 : 32,
      height: isCompactMobile ? 30 : 32,
      borderRadius: isCompactMobile ? 7 : 8,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.cardBgSoft,
    },
    editQtyBox: {
      minWidth: isCompactMobile ? 34 : 38,
      height: isCompactMobile ? 30 : 32,
      borderRadius: isCompactMobile ? 7 : 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.cardBg,
      borderWidth: 1,
      borderColor: palette.borderSoft,
    },
    editQtyText: {
      fontSize: (isCompactMobile ? 13 : 15) * scale,
      fontWeight: '900',
      color: palette.textPrimary,
    },
    editConfirmRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    editConfirmText: {
      fontSize: 12 * scale,
      color: '#c10015',
      fontWeight: '700',
    },
    editConfirmYes: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: '#c10015',
      alignItems: 'center',
      justifyContent: 'center',
    },
    editConfirmNo: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: palette.textSecondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    orderProductActionStack: {
      alignItems: 'flex-end',
      gap: isCompactMobile ? 4 : 6,
    },
    orderProductCustomizeButton: {
      minWidth: isCompactMobile ? 30 : 34,
      height: isCompactMobile ? 30 : 34,
      borderRadius: isCompactMobile ? 8 : 9,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBgSoft,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: isCompactMobile ? 6 : 8,
    },
    mobileProductItemRow: {
      marginTop: 6,
      paddingVertical: isCompactMobile ? 7 : 9,
      paddingHorizontal: isCompactMobile ? 8 : 10,
      borderLeftWidth: 4,
      borderRadius: isCompactMobile ? 9 : 10,
      backgroundColor: palette.cardBgSoft,
    },
    mobileProductText: {
      color: palette.textPrimary,
      fontSize: (isCompactMobile ? 14 : 16) * scale,
      fontWeight: '800',
    },
    mobileProductSubText: {
      color: palette.textSecondary,
      fontSize: (isCompactMobile ? 12 : 13) * scale,
      fontWeight: '700',
    },
    mobileProductQtyText: {
      color: palette.accentInfo,
      fontWeight: '900',
    },
    mobileProductStatusMarker: {
      fontWeight: '900',
    },
    orderProductItemMainRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    orderProductItemLead: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    orderProductThumbWrap: {
      width: isCompactMobile ? 48 : 56,
      height: isCompactMobile ? 48 : 56,
      borderRadius: isCompactMobile ? 10 : 12,
      overflow: 'hidden',
      backgroundColor: palette.cardBg,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    orderProductThumbImage: {
      width: '100%',
      height: '100%',
    },
    orderProductThumbPlaceholder: {
      width: '100%',
      height: '100%',
      backgroundColor: palette.cardBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    orderProductThumbPlaceholderText: {
      color: palette.textSecondary,
      fontSize: (isCompactMobile ? 15 : 18) * scale,
      fontWeight: '900',
    },
    orderProductItemContent: {
      flex: 1,
      minWidth: 0,
    },
    orderProductMetaWrap: {
      marginTop: isCompactMobile ? 4 : 6,
      gap: isCompactMobile ? 3 : 4,
    },
    orderProductQueueBadge: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: isCompactMobile ? 7 : 8,
      paddingVertical: isCompactMobile ? 2 : 3,
      gap: isCompactMobile ? 4 : 6,
    },
    orderProductQueueBadgeDot: {
      width: 7,
      height: 7,
      borderRadius: 999,
    },
    orderProductQueueBadgeText: {
      fontSize: (isCompactMobile ? 9 : 10) * scale,
      fontWeight: '800',
    },
    orderProductItemActions: {
      alignSelf: 'stretch',
      justifyContent: 'center',
    },
    orderProductPriceRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 10,
    },
    orderProductGroupWrap: {
      marginTop: isCompactMobile ? 5 : 7,
      paddingLeft: isCompactMobile ? 4 : 6,
      gap: isCompactMobile ? 3 : 4,
    },
    orderProductGroupTitlePill: {
      alignSelf: 'flex-start',
      borderRadius: 6,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: isCompactMobile ? 6 : 7,
      paddingVertical: 2,
      marginBottom: 1,
    },
    orderProductGroupTitle: {
      color: palette.textSecondary,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    orderProductGroupItem: {
      gap: 2,
      paddingLeft: 4,
    },
    orderProductGroupItemContent: {
      flex: 1,
      minWidth: 0,
    },
    orderProductGroupItemRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    orderProductGroupItemMetaWrap: {
      marginTop: 4,
      gap: 3,
    },
    orderProductGroupItemActions: {
      alignSelf: 'stretch',
      justifyContent: 'center',
    },
    orderProductGroupItemText: {
      flex: 1,
      color: palette.textPrimary,
      fontSize: (isCompactMobile ? 12 : 13) * scale,
      fontWeight: '900',
      lineHeight: isCompactMobile ? 16 : 18,
    },
    orderProductGroupItemMetaText: {
      color: palette.textSecondary,
      fontSize: (isCompactMobile ? 11 : 12) * scale,
      fontWeight: '600',
      lineHeight: isCompactMobile ? 15 : 17,
    },
    orderProductGroupItemPriceText: {
      color: palette.textSecondary,
      fontSize: (isCompactMobile ? 11 : 12) * scale,
      fontWeight: '700',
      lineHeight: isCompactMobile ? 16 : 18,
    },
    mobileBottomActionsWrap: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: isCompactMobile ? 6 : 8,
      backgroundColor: palette.panelBg,
      paddingTop: isCompactMobile ? 6 : 8,
      paddingBottom: isCompactMobile ? 8 : 10,
      paddingHorizontal: isCompactMobile ? 10 : 12,
      borderTopWidth: 1,
      borderTopColor: palette.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 10,
    },
    mobileCancelActionButton: {
      width: isCompactMobile ? 44 : 48,
      height: isCompactMobile ? 44 : 48,
      borderRadius: isCompactMobile ? 10 : 12,
      borderWidth: 1,
      borderColor: palette.danger,
      backgroundColor: palette.dangerBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mobilePrimaryActionButton: {
      flex: 1,
      minHeight: isCompactMobile ? 44 : 48,
      borderRadius: isCompactMobile ? 10 : 12,
      borderWidth: 1,
      borderColor: palette.primary,
      backgroundColor: palette.primary,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.16,
      shadowRadius: 8,
      elevation: 6,
    },
    mobilePrimaryActionText: {
      color: '#FFFFFF',
      fontSize: (isCompactMobile ? 15 : 17) * scale,
      fontWeight: '900',
      letterSpacing: 0.2,
    },
    mobileActionButtonDisabled: {
      opacity: 0.55,
    },
    itemRow: {
      marginTop: 6 * scale,
      paddingVertical: 6 * scale,
      paddingLeft: 9 * scale,
      borderLeftWidth: 5,
      borderRadius: 10,
      backgroundColor: '#101927',
    },
    text: {
      color: '#F8FAFC',
      fontSize: 17 * scale,
      fontWeight: '800',
    },
    subText: {
      color: '#CBD5E1',
      fontSize: 14 * scale,
      fontWeight: '600',
    },
    qtyText: {
      color: '#FACC15',
      fontWeight: '900',
    },
    statusMarker: {
      fontWeight: '900',
    },
    kdsContainer: {
      backgroundColor: palette.appBg,
    },
    food99InfoCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#163047',
      backgroundColor: '#0A1420',
      padding: 12,
      marginBottom: 10,
    },
    food99InfoHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    food99InfoHeaderRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    food99InfoTitle: {
      color: '#E2E8F0',
      fontSize: 15,
      fontWeight: '800',
    },
    food99InfoBadge: {
      color: '#7DD3FC',
      fontSize: 12,
      fontWeight: '700',
    },
    food99InfoText: {
      color: '#CBD5E1',
      fontSize: 13,
      fontWeight: '600',
      marginBottom: 4,
    },
    food99InfoTextStrong: {
      color: '#F8FAFC',
      fontSize: 13,
      fontWeight: '800',
      marginBottom: 4,
    },
    food99InfoHint: {
      color: '#FCD34D',
      fontSize: 12,
      fontWeight: '700',
      marginTop: 6,
    },
    food99RefreshButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: '#1D4ED8',
      backgroundColor: '#0F172A',
      alignItems: 'center',
      justifyContent: 'center',
    },
    food99RefreshButtonDisabled: {
      opacity: 0.55,
    },
    food99SummaryRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 8,
      marginBottom: 2,
    },
    food99SummaryPill: {
      flex: 1,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#1E3A5F',
      backgroundColor: '#0B1220',
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    food99SummaryLabel: {
      color: '#93C5FD',
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      marginBottom: 3,
    },
    food99SummaryValue: {
      color: '#F8FAFC',
      fontSize: 14,
      fontWeight: '800',
    },
    food99SummaryBlock: {
      marginTop: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#1E293B',
      backgroundColor: '#0B1220',
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    food99SummaryTitle: {
      color: '#93C5FD',
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    scheduledDeliveryBanner: {
      marginTop: 8,
      marginBottom: 4,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: '#e67e22',
      backgroundColor: '#451A03',
      paddingHorizontal: 12,
      paddingVertical: 10,
      alignItems: 'center',
    },
    scheduledDeliveryLabel: {
      color: '#FCD34D',
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 1.5,
      textTransform: 'uppercase',
    },
    scheduledDeliveryDate: {
      color: '#FDE68A',
      fontSize: 13,
      fontWeight: '700',
      marginTop: 3,
    },
    taxDocumentBanner: {
      marginTop: 8,
      marginBottom: 4,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: '#0891B2',
      backgroundColor: '#082F49',
      paddingHorizontal: 12,
      paddingVertical: 10,
      alignItems: 'center',
    },
    taxDocumentLabel: {
      color: '#67E8F9',
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      textAlign: 'center',
    },
    taxDocumentText: {
      color: '#CFFAFE',
      fontSize: 13,
      fontWeight: '700',
      marginTop: 3,
      textAlign: 'center',
    },
    cancelReasonModal: {
      width: '100%',
      maxHeight: windowHeight * 0.88,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.modalBg,
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 14,
    },
    cancelReasonBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBgSoft,
      color: palette.accentInfo,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      marginBottom: 10,
    },
    cancelReasonTitle: {
      color: palette.textPrimary,
      fontSize: 22,
      fontWeight: '900',
      marginBottom: 6,
    },
    cancelReasonDescription: {
      color: palette.textSecondary,
      fontSize: 13,
      lineHeight: 19,
      marginBottom: 14,
    },
    cancelReasonLoadingState: {
      minHeight: 120,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    cancelReasonLoadingText: {
      color: palette.textSecondary,
      fontSize: 13,
      fontWeight: '600',
    },
    cancelReasonList: {
      maxHeight: 300,
    },
    cancelReasonListContent: {
      gap: 10,
      paddingBottom: 4,
    },
    cancelReasonOption: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 12,
      paddingVertical: 11,
    },
    cancelReasonOptionSelected: {
      borderColor: palette.accentInfo,
      backgroundColor: palette.cardBg,
    },
    cancelReasonOptionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 4,
    },
    cancelReasonOptionCode: {
      color: palette.accentInfo,
      fontSize: 11,
      fontWeight: '800',
    },
    cancelReasonOptionBadge: {
      color: palette.accent,
      fontSize: 10,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    cancelReasonOptionText: {
      color: palette.textPrimary,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    cancelReasonInputBlock: {
      marginTop: 12,
      marginBottom: 2,
    },
    cancelReasonInputLabel: {
      color: palette.accentInfo,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      marginBottom: 6,
    },
    cancelReasonInput: {
      minHeight: 82,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      color: palette.textPrimary,
      fontSize: 16,
      fontWeight: '700',
      paddingHorizontal: 12,
      paddingVertical: 10,
      textAlignVertical: 'top',
    },
    cancelReasonButtonDanger: {
      borderColor: palette.danger,
      backgroundColor: palette.danger,
    },
    detailsModal: {
      width: '100%',
      maxHeight: windowHeight * 0.84,
      minHeight: 320,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.modalBg,
      paddingHorizontal: 18,
      paddingTop: 16,
      paddingBottom: 14,
    },
    detailsModalFullscreen: {
      flex: 1,
      width: '100%',
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.modalBg,
      paddingHorizontal: 16,
    },
    detailsModalHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 14,
    },
    detailsModalEyebrow: {
      color: palette.accentInfo,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    detailsModalTitle: {
      color: palette.textPrimary,
      fontSize: 26,
      fontWeight: '900',
    },
    detailsModalCloseButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailsModalScroll: {
      flex: 1,
    },
    detailsModalScrollContent: {
      paddingBottom: 20,
      gap: 12,
    },
    detailsModalFullscreenHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      paddingBottom: 12,
      marginBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: palette.borderSoft,
    },
    detailsModalFullscreenHeaderContent: {
      flex: 1,
      minWidth: 0,
    },
    detailsModalFullscreenScroll: {
      flex: 1,
    },
    detailsModalFullscreenScrollContent: {
      paddingBottom: 20,
      gap: 12,
    },
    detailsMarkPaidButton: {
      minHeight: 44,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.accentInfo,
      backgroundColor: palette.accentInfo,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    detailsMarkPaidButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    detailsTabsWrap: {
      width: '100%',
    },
    detailsTabsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: isCompactMobile ? 6 : 8,
      marginBottom: isCompactMobile ? 10 : 12,
    },
    detailsTabButton: {
      flex: isCompactMobile ? 1 : undefined,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: isCompactMobile ? 10 : 12,
      paddingVertical: isCompactMobile ? 7 : 8,
      alignItems: 'center',
    },
    detailsTabButtonActive: {
      borderColor: palette.accentInfo,
      backgroundColor: palette.cardBg,
    },
    detailsTabButtonText: {
      color: palette.textSecondary,
      fontSize: isCompactMobile ? 11 : 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    detailsTabButtonTextActive: {
      color: palette.accentInfo,
    },
    detailsTabContentWrap: {
      width: '100%',
    },
    detailsTabStack: {
      gap: isCompactMobile ? 10 : 12,
    },
    detailsProductSearchStack: {
      gap: isCompactMobile ? 6 : 8,
    },
    detailsProductSearchBox: {
      marginBottom: 0,
    },
    detailsProductSearchHelper: {
      color: palette.textSecondary,
      fontSize: isCompactMobile ? 11 : 12,
      lineHeight: isCompactMobile ? 16 : 18,
      fontWeight: '600',
    },
    detailsProductSearchResults: {
      gap: 0,
    },
    detailsProductSearchResultCard: {
      minHeight: isCompactMobile ? 58 : 64,
      paddingHorizontal: isCompactMobile ? 9 : 10,
      paddingVertical: isCompactMobile ? 8 : 9,
    },
    detailsProductSearchThumb: {
      width: isCompactMobile ? 42 : 46,
      height: isCompactMobile ? 42 : 46,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBg,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      flexShrink: 0,
    },
    detailsProductSearchImage: {
      width: '100%',
      height: '100%',
    },
    detailsProductSearchPrice: {
      color: palette.positive,
      fontSize: isCompactMobile ? 12 : 13,
      fontWeight: '900',
      lineHeight: isCompactMobile ? 16 : 17,
    },
    detailsProductSearchCustomButton: {
      minHeight: isCompactMobile ? 30 : 32,
      borderRadius: 10,
      backgroundColor: palette.textPrimary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: isCompactMobile ? 9 : 11,
      flexShrink: 0,
    },
    detailsProductSearchCustomText: {
      color: palette.cardBg,
      fontSize: isCompactMobile ? 10 : 11,
      fontWeight: '900',
      letterSpacing: 0.2,
    },
    detailsGrid: {
      flexDirection: 'row',
      gap: 10,
      flexWrap: 'wrap',
    },
    detailsCard: {
      flexGrow: 1,
      minWidth: 180,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 12,
      paddingVertical: 11,
    },
    detailsCardLabel: {
      color: palette.accentInfo,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    detailsCardValue: {
      color: palette.textPrimary,
      fontSize: 17,
      fontWeight: '800',
    },
    detailsSection: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 12,
      paddingVertical: 11,
    },
    detailsSectionTitle: {
      color: palette.accentInfo,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      marginBottom: 6,
    },
    detailsInfoText: {
      color: palette.textSecondary,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 19,
      marginBottom: 4,
    },
    detailsInfoTextStrong: {
      color: palette.textPrimary,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 19,
      marginBottom: 4,
    },
    detailsLoadingState: {
      minHeight: 120,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    detailsLoadingText: {
      color: palette.textSecondary,
      fontSize: 13,
      fontWeight: '600',
    },
    detailsItemsSection: {
      flex: 1,
      flexDirection: 'column',
      width: '100%',
    },
    kdsActionRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 8,
    },
    kdsActionButton: {
      flex: 1,
      borderRadius: 10,
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      borderWidth: 1,
    },
    kdsActionPrimary: {
      backgroundColor: '#0B84C6',
      borderColor: '#0B84C6',
    },
    kdsActionDanger: {
      backgroundColor: '#2A1114',
      borderColor: '#7F1D1D',
    },
    kdsActionSuccess: {
      backgroundColor: '#102617',
      borderColor: '#166534',
    },
    kdsActionNeutral: {
      backgroundColor: '#1E293B',
      borderColor: '#334155',
    },
    kdsActionText: {
      color: '#F8FAFC',
      fontSize: 14,
      fontWeight: '700',
    },
    kdsActionButtonDisabled: {
      opacity: 0.6,
    },
    food99InfoWarning: {
      color: palette.dangerText,
      fontSize: 12,
      fontWeight: '700',
      marginTop: 6,
    },
    modalSheetRoot: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: palette.overlay,
      paddingTop: 24,
    },
    modalSheetBackdrop: {
      flex: 1,
    },
    modalSheetWrap: {
      width: '100%',
      maxHeight: windowHeight,
      justifyContent: 'flex-end',
    },
    modalSheetFullscreenWrap: {
      flex: 1,
      width: '100%',
    },
    deliveryCodeModal: {
      width: '100%',
      maxHeight: windowHeight * 0.92,
      minHeight: 360,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.modalBg,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 14,
    },
    deliveryCodeHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
      gap: 10,
    },
    deliveryCodeModalTitle: {
      color: palette.textPrimary,
      fontSize: 24,
      fontWeight: '900',
      marginBottom: 10,
    },
    deliveryCodeCloseButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    deliveryCodeScroll: {
      flex: 1,
    },
    deliveryCodeScrollContent: {
      paddingBottom: 8,
    },
    deliveryCodeStepBadge: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.borderSoft,
      backgroundColor: palette.cardBgSoft,
      color: palette.accentInfo,
      fontSize: 11,
      fontWeight: '800',
      paddingHorizontal: 10,
      paddingVertical: 5,
      marginBottom: 0,
      overflow: 'hidden',
      textTransform: 'uppercase',
    },
    deliveryCodeTitle: {
      color: palette.textPrimary,
      fontSize: 20,
      fontWeight: '800',
      marginBottom: 8,
    },
    deliveryCodeDescription: {
      color: palette.textSecondary,
      fontSize: 13,
      lineHeight: 20,
      marginBottom: 14,
    },
    assignmentSearchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isCompactMobile ? 6 : 8,
      borderRadius: isCompactMobile ? 10 : 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: isCompactMobile ? 10 : 12,
      minHeight: isCompactMobile ? 42 : 48,
      marginBottom: isCompactMobile ? 10 : 14,
    },
    assignmentSearchInput: {
      flex: 1,
      color: palette.textPrimary,
      fontSize: isCompactMobile ? 13 : 14,
      paddingVertical: 0,
    },
    assignmentEmptyState: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: isCompactMobile ? 12 : 14,
      paddingVertical: isCompactMobile ? 12 : 14,
      gap: 6,
      marginBottom: 12,
      alignItems: 'flex-start',
    },
    assignmentEmptyStateTitle: {
      color: palette.textPrimary,
      fontSize: 15,
      fontWeight: '800',
    },
    assignmentEmptyStateText: {
      color: palette.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '600',
    },
    assignmentOptionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isCompactMobile ? 8 : 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: isCompactMobile ? 12 : 14,
      paddingVertical: isCompactMobile ? 10 : 12,
      marginBottom: isCompactMobile ? 8 : 10,
    },
    assignmentOptionCardSelected: {
      borderColor: palette.accentInfo,
      backgroundColor: palette.cardBg,
    },
    assignmentOptionTextWrap: {
      flex: 1,
      gap: 3,
    },
    assignmentOptionTitle: {
      color: palette.textPrimary,
      fontSize: isCompactMobile ? 13 : 14,
      fontWeight: '800',
      lineHeight: isCompactMobile ? 18 : 19,
    },
    assignmentOptionMeta: {
      color: palette.textSecondary,
      fontSize: isCompactMobile ? 11 : 12,
      fontWeight: '600',
      lineHeight: isCompactMobile ? 16 : 18,
    },
    assignmentOptionBadge: {
      color: palette.accentInfo,
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    assignmentQuickActionCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.accentInfo,
      backgroundColor: palette.cardBg,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginTop: 2,
      marginBottom: 6,
    },
    assignmentQuickActionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 6,
    },
    assignmentQuickActionTitle: {
      color: palette.accentInfo,
      fontSize: 13,
      fontWeight: '900',
    },
    assignmentQuickActionText: {
      color: palette.textSecondary,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 18,
    },
    assignmentFormInput: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      color: palette.textPrimary,
      minHeight: 48,
      paddingHorizontal: 14,
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 10,
    },
    assignmentFormRow: {
      flexDirection: 'row',
      gap: 8,
    },
    assignmentContextCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 12,
    },
    assignmentContextText: {
      flex: 1,
      color: palette.textPrimary,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 18,
    },
    deliveryCodeInput: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      color: palette.textPrimary,
      minHeight: 52,
      paddingHorizontal: 16,
      fontSize: 24,
      fontWeight: '800',
      letterSpacing: 6,
      textAlign: 'center',
      marginBottom: 10,
    },
    deliveryCodeHelper: {
      color: palette.textSecondary,
      fontSize: 12,
      fontWeight: '600',
      marginBottom: 14,
    },
    deliveryCodeActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 8,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.borderSoft,
    },
    deliveryCodeMetaCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 12,
    },
    deliveryCodeMetaRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 12,
    },
    deliveryCodeMetaCardCompact: {
      flex: 1,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    deliveryCodeMetaLabel: {
      color: palette.textSecondary,
      fontSize: 11,
      fontWeight: '700',
      marginBottom: 4,
      textTransform: 'uppercase',
    },
    deliveryCodeMetaValue: {
      color: palette.textPrimary,
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: 2,
    },
    deliveryCodeMetaValueCompact: {
      color: palette.textPrimary,
      fontSize: 18,
      fontWeight: '800',
      letterSpacing: 1.5,
    },
    deliveryLocatorHero: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 12,
    },
    deliveryLocatorHeroValue: {
      color: palette.textPrimary,
      fontSize: 28,
      fontWeight: '900',
      letterSpacing: 4,
      marginBottom: 8,
    },
    deliveryLocatorHeroHelper: {
      color: palette.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      marginBottom: 10,
    },
    deliveryLinkCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 12,
    },
    deliveryLinkUrl: {
      color: palette.accentInfo,
      fontSize: 12,
      lineHeight: 18,
      marginBottom: 10,
    },
    deliveryLinkActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    deliveryLinkActionButton: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.cardBg,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    deliveryLinkActionText: {
      color: palette.textPrimary,
      fontSize: 12,
      fontWeight: '700',
    },
    deliveryLinkPrimaryButton: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.accentInfo,
      backgroundColor: palette.cardBg,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    deliveryLinkPrimaryButtonText: {
      color: palette.accentInfo,
      fontSize: 12,
      fontWeight: '700',
    },
    deliveryCodeButton: {
      flex: 1,
      minHeight: 44,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
    },
    deliveryCodeButtonSecondary: {
      borderColor: palette.border,
      backgroundColor: palette.cardBgSoft,
    },
    deliveryCodeButtonPrimary: {
      borderColor: palette.primary,
      backgroundColor: palette.primary,
    },
    deliveryCodeButtonSecondaryText: {
      color: palette.textPrimary,
      fontSize: 14,
      fontWeight: '700',
    },
    deliveryCodeButtonPrimaryText: {
      color: '#F8FAFC',
      fontSize: 14,
      fontWeight: '800',
    },
  })
  )
}

export default createStyles

export const inlineStyle_2116_14 = {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 4,
};

export const inlineStyle_2121_14 = (
  {
    ppcColors: ppcColors,
  },
) => ({
  flexDirection: 'row',
  alignItems: 'center',
  gap: 4,
  paddingVertical: 6,
  paddingHorizontal: 10,
  borderRadius: 8,
  backgroundColor: ppcColors.primary,
});

export const inlineStyle_2128_20 = {
  color: '#fff',
  fontSize: 12,
  fontWeight: '700',
};

export const inlineStyle_2181_30 = {
  flex: 1,
};

export const inlineStyle_2712_14 = {
  flex: 1,
};

export const inlineStyle_2718_20 = {
  flexDirection: 'row',
  alignItems: 'center',
};

export const inlineStyle_2725_26 = {
  color: '#fff',
  marginLeft: 8,
};

export const inlineStyle_2737_26 = {
  color: '#fff',
  marginLeft: 8,
};

export const inlineStyle_2748_24 = {
  color: '#fff',
  marginLeft: 8,
};

export const inlineStyle_2782_34 = {
  flex: 1,
};

export const inlineStyle_2768_24 = {
  paddingBottom: 20,
};
