import {Platform, StyleSheet} from 'react-native'

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#0F172A',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.08,
    shadowRadius: 20,
  },
  android: {elevation: 4},
  web: {boxShadow: '0 16px 40px rgba(15,23,42,0.08)'},
})

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 20,
    gap: 16,
  },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    gap: 16,
    ...cardShadow,
  },
  heroHeader: {
    flexDirection: 'row',
    gap: 14,
  },
  heroIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroCopy: {
    flex: 1,
    gap: 4,
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0F172A',
  },
  heroText: {
    fontSize: 13,
    lineHeight: 19,
    color: '#64748B',
  },
  heroActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  primaryAction: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    minHeight: 48,
    paddingHorizontal: 18,
  },
  primaryActionText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  secondaryAction: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    minHeight: 48,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
  },
  secondaryActionText: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '700',
  },
  actionDisabled: {
    opacity: 0.55,
  },
  loadingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 18,
  },
  loadingText: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
  },
  centerState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  centerStateTitle: {
    marginTop: 14,
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
  },
  centerStateText: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 21,
    color: '#64748B',
    textAlign: 'center',
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 28,
    alignItems: 'center',
    gap: 8,
    ...cardShadow,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 21,
    color: '#64748B',
    textAlign: 'center',
  },
  primaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    gap: 14,
    ...cardShadow,
  },
  primaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  primaryBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  primaryBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0369A1',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  inlineLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  inlineLinkText: {
    fontSize: 13,
    fontWeight: '800',
  },
  primaryCode: {
    fontSize: 28,
    fontWeight: '900',
    color: '#0F172A',
  },
  primarySubtitle: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
  },
  metricsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricCard: {
    flexGrow: 1,
    minWidth: 96,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 4,
  },
  metricLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
  },
  metricValueSuccess: {
    color: '#16A34A',
  },
  metricValueDanger: {
    color: '#DC2626',
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    gap: 14,
    ...cardShadow,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
  },
  sectionMeta: {
    minWidth: 30,
    textAlign: 'center',
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '800',
    color: '#334155',
  },
  rowList: {
    gap: 10,
  },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  invoiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  listRowMain: {
    flex: 1,
    gap: 4,
  },
  invoiceMain: {
    flex: 1,
    gap: 4,
  },
  listRowTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  listRowSubtitle: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '600',
  },
  listRowMeta: {
    alignItems: 'flex-end',
    gap: 8,
  },
  invoiceMeta: {
    alignItems: 'flex-end',
    gap: 8,
  },
  listRowAmount: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0F172A',
  },
  primaryChip: {
    borderRadius: 999,
    backgroundColor: '#ECFCCB',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  primaryChipText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#3F6212',
  },
  invoiceStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  invoiceStatusBadgeClosed: {
    backgroundColor: '#DCFCE7',
  },
  invoiceStatusBadgeOpen: {
    backgroundColor: '#FEF3C7',
  },
  invoiceStatusText: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
  },
  invoiceStatusTextClosed: {
    color: '#15803D',
  },
  invoiceStatusTextOpen: {
    color: '#B45309',
  },
  cardItem: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 10,
    backgroundColor: '#FFFFFF',
  },
  emptySectionText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#64748B',
  },
  footerActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingBottom: 8,
  },
  footerPrimaryButton: {
    flex: 1,
    minWidth: 180,
    minHeight: 52,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
  },
  footerPrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  footerSecondaryButton: {
    flex: 1,
    minWidth: 180,
    minHeight: 52,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
  },
  footerSecondaryButtonText: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
})

export default styles
