import {Platform, StyleSheet} from 'react-native'

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#020617',
    flex: 1,
  },
  header: {
    paddingBottom: 20,
    paddingHorizontal: 20,
    paddingTop: Platform.select({android: 24, ios: 56, default: 24}),
  },
  title: {
    color: '#F8FAFC',
    fontSize: 24,
    fontWeight: '800',
  },
  subtitle: {
    color: '#CBD5E1',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  cameraWrap: {
    borderRadius: 28,
    flex: 1,
    marginHorizontal: 20,
    overflow: 'hidden',
    position: 'relative',
  },
  camera: {
    backgroundColor: '#0F172A',
    flex: 1,
  },
  overlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  guideFrame: {
    borderColor: 'rgba(255, 255, 255, 0.88)',
    borderRadius: 28,
    borderWidth: 2,
    height: 240,
    maxWidth: 360,
    width: '84%',
  },
  guideTextWrap: {
    alignItems: 'center',
    bottom: 36,
    left: 20,
    position: 'absolute',
    right: 20,
  },
  guideText: {
    color: '#E2E8F0',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  footer: {
    gap: 14,
    paddingBottom: Platform.select({android: 26, ios: 34, default: 26}),
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  messageBox: {
    alignItems: 'center',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  messageBoxError: {
    backgroundColor: 'rgba(239, 68, 68, 0.18)',
    borderColor: 'rgba(248, 113, 113, 0.5)',
    borderWidth: 1,
  },
  messageBoxInfo: {
    backgroundColor: 'rgba(14, 165, 233, 0.16)',
    borderColor: 'rgba(56, 189, 248, 0.45)',
    borderWidth: 1,
  },
  messageText: {
    color: '#F8FAFC',
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'flex-end',
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: 'rgba(203, 213, 225, 0.55)',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 50,
    minWidth: 132,
    paddingHorizontal: 20,
  },
  secondaryButtonText: {
    color: '#E2E8F0',
    fontSize: 14,
    fontWeight: '800',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#0EA5E9',
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 50,
    minWidth: 132,
    paddingHorizontal: 20,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    gap: 14,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  centerStateTitle: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  centerStateDescription: {
    color: '#CBD5E1',
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 360,
    textAlign: 'center',
  },
  loadingText: {
    color: '#CBD5E1',
    fontSize: 14,
    fontWeight: '700',
  },
  busyOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(2, 6, 23, 0.6)',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
})

export default styles
