import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(2, 39, 54, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  card: {
    width: '100%',
    maxWidth: 480,
    maxHeight: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DCE7F3',
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E8EEF5',
  },
  title: {
    fontSize: 16,
    fontWeight: '800',
    color: '#022736',
    flex: 1,
    paddingRight: 8,
  },
  closeLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0B6E99',
  },
  body: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  label: {
    marginTop: 10,
    fontSize: 12,
    fontWeight: '700',
    color: '#5B6B7C',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  value: {
    marginTop: 4,
    fontSize: 15,
    fontWeight: '600',
    color: '#022736',
  },
  input: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: '#DCE7F3',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: '#022736',
    backgroundColor: '#F8FAFC',
  },
  reasonInput: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
  errorText: {
    marginTop: 12,
    fontSize: 13,
    fontWeight: '600',
    color: '#B42318',
  },
  previewBox: {
    marginTop: 14,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#F0F7FB',
    borderWidth: 1,
    borderColor: '#C5DCEC',
  },
  auditBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  previewTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#022736',
    marginBottom: 6,
  },
  previewLine: {
    fontSize: 13,
    color: '#334155',
    marginTop: 2,
  },
  previewWarn: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    color: '#B54708',
  },
  footer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#E8EEF5',
  },
  spinner: {
    marginRight: 8,
  },
  button: {
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButton: {
    backgroundColor: '#0B6E99',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 13,
  },
  secondaryButton: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#DCE7F3',
  },
  secondaryButtonText: {
    color: '#022736',
    fontWeight: '700',
    fontSize: 13,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
});
