import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  modalAlignEnd: {
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    maxHeight: '92%',
    width: '100%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    gap: 12,
  },
  headerTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: '#0F172A',
    fontSize: 17,
    fontWeight: '800',
  },
  subtitle: {
    color: '#64748B',
    fontSize: 12,
    marginTop: 4,
    lineHeight: 17,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 18,
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  searchBox: {
    flex: 1,
    minHeight: 42,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F8FAFC',
  },
  searchInput: {
    flex: 1,
    minWidth: 80,
    color: '#0F172A',
    fontSize: 14,
  },
  searchClearButton: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadButton: {
    minHeight: 42,
    borderRadius: 10,
    backgroundColor: '#0F172A',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  uploadButtonDisabled: {
    opacity: 0.72,
  },
  uploadButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
  },
  refreshButton: {
    width: 42,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  section: {
    marginTop: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
  sectionMeta: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
  },
  emptyState: {
    minHeight: 110,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    backgroundColor: '#F8FAFC',
  },
  emptyStateText: {
    color: '#64748B',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  attachmentList: {
    gap: 10,
  },
  attachmentCard: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#fff',
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  attachmentCardAttached: {
    borderColor: '#86EFAC',
    backgroundColor: '#F0FDF4',
  },
  attachmentPreview: {
    width: 78,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#E2E8F0',
  },
  attachmentImage: {
    width: '100%',
    height: '100%',
  },
  attachmentIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E2E8F0',
  },
  attachmentBody: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
  },
  attachmentName: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  attachmentMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  attachmentBadge: {
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: '800',
  },
  attachmentBadgeNeutral: {
    backgroundColor: '#E2E8F0',
    color: '#475569',
  },
  attachmentBadgePrimary: {
    backgroundColor: '#DBEAFE',
    color: '#1D4ED8',
  },
  attachmentBadgeAttached: {
    backgroundColor: '#DCFCE7',
    color: '#15803D',
  },
  attachmentBadgeDanger: {
    backgroundColor: '#FEE2E2',
    color: '#B91C1C',
  },
  attachmentActions: {
    padding: 10,
    gap: 8,
    justifyContent: 'center',
  },
  iconActionButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#fff',
  },
  iconActionButtonPrimary: {
    backgroundColor: '#0F172A',
    borderColor: '#0F172A',
  },
  iconActionButtonDanger: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
  },
  loadMoreButton: {
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  loadMoreButtonText: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
  },
  loadingState: {
    minHeight: 110,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingText: {
    color: '#64748B',
    fontSize: 13,
  },
});

export default styles;
